package userActivity;

import com.ftn.sbnz.model.events.enums.AddCampaignType
import com.ftn.sbnz.model.events.AddCampaignEvent
import java.util.List
import java.util.Map
import com.ftn.sbnz.model.models.enums.Level;
import com.ftn.sbnz.model.models.User;
import com.ftn.sbnz.model.models.UserActivity;
import com.ftn.sbnz.model.models.Campaign;
import com.ftn.sbnz.model.models.SearchData;
import com.ftn.sbnz.model.models.CampaignTheme;
import com.ftn.sbnz.model.events.SearchEvent;

import static java.util.stream.Collectors.*
import java.util.HashMap
import com.ftn.sbnz.model.models.enums.GameplayStyle
import com.ftn.sbnz.model.models.enums.Theme
import com.ftn.sbnz.model.models.CampaignMatch
import java.util.Collections
import java.util.Comparator
import java.util.ArrayList;

global List<CampaignMatch> searchResults;

rule "Match campaigns with search data"
when
    $event : SearchEvent(
        $searchData : getSearchData()
    )
    $campaigns : List() from collect(Campaign())
then
    for (Object o : $campaigns) {
        int matchCount = 0;
        Campaign c = (Campaign) o;
        if (!$searchData.getTheme().isEmpty() && $searchData.getTheme().contains(c.getTheme().name())) {
            matchCount++;
        }
        if (!$searchData.getLevel().isEmpty() && $searchData.getLevel().contains(c.getLevel().name())) {
            matchCount++;
        }
        if (!$searchData.getGameplayStyle().isEmpty() && $searchData.getGameplayStyle().contains(c.getGameplayStyle().name())) {
            matchCount++;
        }
        if (!$searchData.getPartySize().isEmpty()) {
            int searchPartySize = Integer.parseInt($searchData.getPartySize().get(0));
            if (Math.abs(searchPartySize - c.getPartySize()) < 2) {
                matchCount++;
            }
        }
        CampaignMatch campaignMatch = new CampaignMatch(c, matchCount);
        insert(campaignMatch);
    }
end

rule "Get top 5 campaigns"
salience -1
when
    $campaignMatches : List() from collect (CampaignMatch())
then
    Collections.sort($campaignMatches, new Comparator<CampaignMatch>() {
        public int compare(CampaignMatch cm1, CampaignMatch cm2) {
            return cm2.getMatchCount() - cm1.getMatchCount();
        }
    });

    int j = 0;
    List<Campaign> top12 = new ArrayList<>();
    for (Object o : $campaignMatches) {
        CampaignMatch cm = (CampaignMatch) o;
        top12.add(cm.getCampaign());
        j++;
        if (j >= 12) {
            break;
        }
    }

    searchResults.clear();
    searchResults.addAll(top12);
end


rule 'playing a lot of the same difficulty in the last month, here is some more'
no-loop when
    $user: User()
    $history: UserActivity(recommendedThisMonth == false) from $user.getHistory()
    $campaigns : List() from collect(Campaign())
    $e: AddCampaignEvent(
        $user == user,
        $campaign: campaign,
        type == AddCampaignType.PLAY
        )
        $level: Level() from $campaign.getLevel()
    Number(intValue > 1) from accumulate(
        $event: AddCampaignEvent(
        $user == user,
        $level == campaign.getLevel(),
        type == AddCampaignType.PLAY,
        $e != this, this after[2s, 30d] $e),
        count($event)
    )
then
    Campaign cam = null;
    for (Object o : $campaigns) {
        Campaign c = (Campaign) o;
        if (c.getLevel() == $level)
            {
                cam = c;
                break;
            }
    }
    modify($user){recommendNew(cam)}
    modify($history){setRecommendedThisMonth(true)};
end

rule 'playing a lot of the same theme in the last month, here is some more'
no-loop when
    $user: User()
    $history: UserActivity(recommendedThisMonth == false) from $user.getHistory()
    $campaigns : List() from collect(Campaign())
    $e: AddCampaignEvent(
        $user == user,
        $campaign: campaign,
        type == AddCampaignType.PLAY
        )
        $theme: Theme() from $campaign.getTheme()
        Number(intValue > 1) from accumulate(
        $event: AddCampaignEvent(
        $user == user,
        $theme == campaign.getTheme(),
        type == AddCampaignType.PLAY,
        $e != this, this after[2s, 30d] $e),
        count($event)
    )
then
    Campaign cam = null;
    for (Object o : $campaigns) {
        Campaign c = (Campaign) o;
        if (c.getTheme() == $theme)
            {
                cam = c;
                break;
            }
    }
    modify($user){recommendNew(cam)}
    modify($history){setRecommendedThisMonth(true)};
end


rule 'playing a lot of the same style in the last month, here is some more'
no-loop when
    $user: User()
    $history: UserActivity(recommendedThisMonth == false) from $user.getHistory()
    $campaigns : List() from collect(Campaign())
    $e: AddCampaignEvent(
        $user == user,
        $campaign: campaign,
        type == AddCampaignType.PLAY
        )
        $style: GameplayStyle() from $campaign.getGameplayStyle()
    Number(intValue > 1) from accumulate(
        $event: AddCampaignEvent(
        $user == user,
        $style == campaign.getGameplayStyle(),
        type == AddCampaignType.PLAY,
        $e != this, this after[2s, 30d] $e),
        count($event)
    )
then
    Campaign cam = null;
    for (Object o : $campaigns) {
        Campaign c = (Campaign) o;
        if (c.getGameplayStyle() == $style)
            {
                cam = c;
                break;
            }
    }
    modify($user){recommendNew(cam)}
    modify($history){setRecommendedThisMonth(true)};
end

rule 'new campaign with the same spirit'
no-loop
when
    $campaign: Campaign()
    $user: User()
    $preference: UserActivity(
    $preferredLevels: getLevels(),
    $preferredStyles: getStyles(),
    $preferredThemes: getThemes()
    ) from $user.getPreference()
    eval(
        $preferredLevels.contains($campaign.getLevel()) ||
        $preferredStyles.contains($campaign.getGameplayStyle()) ||
        $preferredThemes.contains($campaign.getTheme())
    )
    $e: AddCampaignEvent(
        $user == user,
        type == AddCampaignType.LIKE
        )
        $style: GameplayStyle() from $campaign.getGameplayStyle()
    Number(intValue > 1) from accumulate(
        $event: AddCampaignEvent(
        $user == user,
        $style == campaign.getGameplayStyle(),
        type == AddCampaignType.LIKE,
        $e != this, this after[2s, 90d] $e),
        count($event)
    )
then
    modify($user){recommendNew($campaign)}
end
