CREATE DATABASE mastermindnd;
CREATE USER pera WITH PASSWORD 'pera123';
GRANT ALL PRIVILEGES ON DATABASE casa TO pera;
GRANT USAGE ON SCHEMA public TO pera;
GRANT CREATE ON SCHEMA public TO pera;
ALTER DATABASE casa OWNER TO pera;
GRANT CONNECT ON DATABASE casa TO pera;